name: dvproductions
favicon: null
layout_spectrum: 0.89865
typography_spectrum: 0.7180389475543052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1275c9'
    - '#dbe0e6'
    - '#8fbada'
    - '#432b17'
    - '#9e735e'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
