name: dvproductions
favicon: null
layout_spectrum: 0.7960336848627776
typography_spectrum: 0.7180389475543052
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010002'
    - '#3c454c'
    - '#787677'
    - '#a1a0a5'
    - '#faf8f9'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
